/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteTutorialsRouteImport } from './routes/_site.tutorials'
import { Route as SiteTrendingRouteImport } from './routes/_site.trending'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as SiteStatusRouteImport } from './routes/_site.status'
import { Route as SiteShowcaseRouteImport } from './routes/_site.showcase'
import { Route as SiteRoadmapRouteImport } from './routes/_site.roadmap'
import { Route as SiteReferralProgramRouteImport } from './routes/_site.referral-program'
import { Route as SitePromptMarketplaceRouteImport } from './routes/_site.prompt-marketplace'
import { Route as SitePromptLibraryRouteImport } from './routes/_site.prompt-library'
import { Route as SitePrivacyRouteImport } from './routes/_site.privacy'
import { Route as SitePricingRouteImport } from './routes/_site.pricing'
import { Route as SitePressKitRouteImport } from './routes/_site.press-kit'
import { Route as SiteNewRouteImport } from './routes/_site.new'
import { Route as SiteModelsRouteImport } from './routes/_site.models'
import { Route as SiteLeaderboardRouteImport } from './routes/_site.leaderboard'
import { Route as SiteIntegrationsRouteImport } from './routes/_site.integrations'
import { Route as SiteHelpRouteImport } from './routes/_site.help'
import { Route as SiteFeaturesRouteImport } from './routes/_site.features'
import { Route as SiteFaqsRouteImport } from './routes/_site.faqs'
import { Route as SiteExploreRouteImport } from './routes/_site.explore'
import { Route as SiteEventsRouteImport } from './routes/_site.events'
import { Route as SiteEnterpriseRouteImport } from './routes/_site.enterprise'
import { Route as SiteDocumentationRouteImport } from './routes/_site.documentation'
import { Route as SiteDmcaRouteImport } from './routes/_site.dmca'
import { Route as SiteCreatorProgramRouteImport } from './routes/_site.creator-program'
import { Route as SiteCookiesRouteImport } from './routes/_site.cookies'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteCommunityRouteImport } from './routes/_site.community'
import { Route as SiteChangelogRouteImport } from './routes/_site.changelog'
import { Route as SiteChallengesRouteImport } from './routes/_site.challenges'
import { Route as SiteCareersRouteImport } from './routes/_site.careers'
import { Route as SiteBlogsRouteImport } from './routes/_site.blogs'
import { Route as SiteApiAccessRouteImport } from './routes/_site.api-access'
import { Route as SiteAffiliateProgramRouteImport } from './routes/_site.affiliate-program'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as AuthWelcomeRouteImport } from './routes/_auth.welcome'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth.verify-otp'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthRecoverRouteImport } from './routes/_auth.recover'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as DashDashboardIndexRouteImport } from './routes/_dash.dashboard.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as SiteToolsWallpaperRouteImport } from './routes/_site.tools.wallpaper'
import { Route as SiteToolsUpscalerRouteImport } from './routes/_site.tools.upscaler'
import { Route as SiteToolsThumbnailRouteImport } from './routes/_site.tools.thumbnail'
import { Route as SiteToolsTextToImageRouteImport } from './routes/_site.tools.text-to-image'
import { Route as SiteToolsStickerRouteImport } from './routes/_site.tools.sticker'
import { Route as SiteToolsPromptEnhancerRouteImport } from './routes/_site.tools.prompt-enhancer'
import { Route as SiteToolsPosterRouteImport } from './routes/_site.tools.poster'
import { Route as SiteToolsMockupRouteImport } from './routes/_site.tools.mockup'
import { Route as SiteToolsLogoRouteImport } from './routes/_site.tools.logo'
import { Route as SiteToolsInteriorRouteImport } from './routes/_site.tools.interior'
import { Route as SiteToolsImageToImageRouteImport } from './routes/_site.tools.image-to-image'
import { Route as SiteToolsFashionRouteImport } from './routes/_site.tools.fashion'
import { Route as SiteToolsFaceEnhancerRouteImport } from './routes/_site.tools.face-enhancer'
import { Route as SiteToolsBackgroundRemoverRouteImport } from './routes/_site.tools.background-remover'
import { Route as SiteToolsAvatarRouteImport } from './routes/_site.tools.avatar'
import { Route as SiteToolsAnimeRouteImport } from './routes/_site.tools.anime'
import { Route as SiteBlogSlugRouteImport } from './routes/_site.blog.$slug'
import { Route as DashDashboardUploadsRouteImport } from './routes/_dash.dashboard.uploads'
import { Route as DashDashboardTeamRouteImport } from './routes/_dash.dashboard.team'
import { Route as DashDashboardSubscriptionRouteImport } from './routes/_dash.dashboard.subscription'
import { Route as DashDashboardSettingsRouteImport } from './routes/_dash.dashboard.settings'
import { Route as DashDashboardScheduledRouteImport } from './routes/_dash.dashboard.scheduled'
import { Route as DashDashboardReferralsRouteImport } from './routes/_dash.dashboard.referrals'
import { Route as DashDashboardPublicGalleryRouteImport } from './routes/_dash.dashboard.public-gallery'
import { Route as DashDashboardPromptsRouteImport } from './routes/_dash.dashboard.prompts'
import { Route as DashDashboardProfileRouteImport } from './routes/_dash.dashboard.profile'
import { Route as DashDashboardNotificationsRouteImport } from './routes/_dash.dashboard.notifications'
import { Route as DashDashboardMessagesRouteImport } from './routes/_dash.dashboard.messages'
import { Route as DashDashboardHistoryRouteImport } from './routes/_dash.dashboard.history'
import { Route as DashDashboardGenerateRouteImport } from './routes/_dash.dashboard.generate'
import { Route as DashDashboardGalleryRouteImport } from './routes/_dash.dashboard.gallery'
import { Route as DashDashboardFollowingRouteImport } from './routes/_dash.dashboard.following'
import { Route as DashDashboardFavoritesRouteImport } from './routes/_dash.dashboard.favorites'
import { Route as DashDashboardEarningsRouteImport } from './routes/_dash.dashboard.earnings'
import { Route as DashDashboardDownloadsRouteImport } from './routes/_dash.dashboard.downloads'
import { Route as DashDashboardCreditsRouteImport } from './routes/_dash.dashboard.credits'
import { Route as DashDashboardCommunityRouteImport } from './routes/_dash.dashboard.community'
import { Route as DashDashboardCollectionsRouteImport } from './routes/_dash.dashboard.collections'
import { Route as DashDashboardCanvasRouteImport } from './routes/_dash.dashboard.canvas'
import { Route as DashDashboardBrandKitRouteImport } from './routes/_dash.dashboard.brand-kit'
import { Route as DashDashboardBillingRouteImport } from './routes/_dash.dashboard.billing'
import { Route as DashDashboardApiKeysRouteImport } from './routes/_dash.dashboard.api-keys'
import { Route as DashDashboardAnalyticsRouteImport } from './routes/_dash.dashboard.analytics'
import { Route as DashDashboardAiToolsRouteImport } from './routes/_dash.dashboard.ai-tools'
import { Route as AuthOnboardingThemeRouteImport } from './routes/_auth.onboarding.theme'
import { Route as AuthOnboardingStyleRouteImport } from './routes/_auth.onboarding.style'
import { Route as AuthOnboardingInterestsRouteImport } from './routes/_auth.onboarding.interests'
import { Route as AuthOnboardingFirstPromptRouteImport } from './routes/_auth.onboarding.first-prompt'
import { Route as AuthOnboardingCategoriesRouteImport } from './routes/_auth.onboarding.categories'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminRevenueRouteImport } from './routes/_admin.admin.revenue'
import { Route as AdminAdminReportedRouteImport } from './routes/_admin.admin.reported'
import { Route as AdminAdminPlansRouteImport } from './routes/_admin.admin.plans'
import { Route as AdminAdminNotificationsRouteImport } from './routes/_admin.admin.notifications'
import { Route as AdminAdminModerationRouteImport } from './routes/_admin.admin.moderation'
import { Route as AdminAdminModelsRouteImport } from './routes/_admin.admin.models'
import { Route as AdminAdminFeatureFlagsRouteImport } from './routes/_admin.admin.feature-flags'
import { Route as AdminAdminCreditsRouteImport } from './routes/_admin.admin.credits'
import { Route as AdminAdminBlogsRouteImport } from './routes/_admin.admin.blogs'
import { Route as AdminAdminBannersRouteImport } from './routes/_admin.admin.banners'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin.admin.analytics'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTutorialsRoute = SiteTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTrendingRoute = SiteTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStatusRoute = SiteStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShowcaseRoute = SiteShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRoadmapRoute = SiteRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReferralProgramRoute = SiteReferralProgramRouteImport.update({
  id: '/referral-program',
  path: '/referral-program',
  getParentRoute: () => SiteRoute,
} as any)
const SitePromptMarketplaceRoute = SitePromptMarketplaceRouteImport.update({
  id: '/prompt-marketplace',
  path: '/prompt-marketplace',
  getParentRoute: () => SiteRoute,
} as any)
const SitePromptLibraryRoute = SitePromptLibraryRouteImport.update({
  id: '/prompt-library',
  path: '/prompt-library',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SitePressKitRoute = SitePressKitRouteImport.update({
  id: '/press-kit',
  path: '/press-kit',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNewRoute = SiteNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SiteRoute,
} as any)
const SiteModelsRoute = SiteModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLeaderboardRoute = SiteLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIntegrationsRoute = SiteIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SiteRoute,
} as any)
const SiteHelpRoute = SiteHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFeaturesRoute = SiteFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqsRoute = SiteFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExploreRoute = SiteExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEventsRoute = SiteEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEnterpriseRoute = SiteEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDocumentationRoute = SiteDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDmcaRoute = SiteDmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCreatorProgramRoute = SiteCreatorProgramRouteImport.update({
  id: '/creator-program',
  path: '/creator-program',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCookiesRoute = SiteCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCommunityRoute = SiteCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => SiteRoute,
} as any)
const SiteChangelogRoute = SiteChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => SiteRoute,
} as any)
const SiteChallengesRoute = SiteChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCareersRoute = SiteCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogsRoute = SiteBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => SiteRoute,
} as any)
const SiteApiAccessRoute = SiteApiAccessRouteImport.update({
  id: '/api-access',
  path: '/api-access',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAffiliateProgramRoute = SiteAffiliateProgramRouteImport.update({
  id: '/affiliate-program',
  path: '/affiliate-program',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const AuthWelcomeRoute = AuthWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecoverRoute = AuthRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const DashDashboardIndexRoute = DashDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteToolsWallpaperRoute = SiteToolsWallpaperRouteImport.update({
  id: '/tools/wallpaper',
  path: '/tools/wallpaper',
  getParentRoute: () => SiteRoute,
} as any)
const SiteToolsUpscalerRoute = SiteToolsUpscalerRouteImport.update({
  id: '/tools/upscaler',
  path: '/tools/upscaler',
  getParentRoute: () => SiteRoute,
} as any)
const SiteToolsThumbnailRoute = SiteToolsThumbnailRouteImport.update({
  id: '/tools/thumbnail',
  path: '/tools/thumbnail',
  getParentRoute: () => SiteRoute,
} as any)
const SiteToolsTextToImageRoute = SiteToolsTextToImageRouteImport.update({
  id: '/tools/text-to-image',
  path: '/tools/text-to-image',
  getParentRoute: () => SiteRoute,
} as any)
const SiteToolsStickerRoute = SiteToolsStickerRouteImport.update({
  id: '/tools/sticker',
  path: '/tools/sticker',
  getParentRoute: () => SiteRoute,
} as any)
const SiteToolsPromptEnhancerRoute = SiteToolsPromptEnhancerRouteImport.update({
  id: '/tools/prompt-enhancer',
  path: '/tools/prompt-enhancer',
  getParentRoute: () => SiteRoute,
} as any)
const SiteToolsPosterRoute = SiteToolsPosterRouteImport.update({
  id: '/tools/poster',
  path: '/tools/poster',
  getParentRoute: () => SiteRoute,
} as any)
const SiteToolsMockupRoute = SiteToolsMockupRouteImport.update({
  id: '/tools/mockup',
  path: '/tools/mockup',
  getParentRoute: () => SiteRoute,
} as any)
const SiteToolsLogoRoute = SiteToolsLogoRouteImport.update({
  id: '/tools/logo',
  path: '/tools/logo',
  getParentRoute: () => SiteRoute,
} as any)
const SiteToolsInteriorRoute = SiteToolsInteriorRouteImport.update({
  id: '/tools/interior',
  path: '/tools/interior',
  getParentRoute: () => SiteRoute,
} as any)
const SiteToolsImageToImageRoute = SiteToolsImageToImageRouteImport.update({
  id: '/tools/image-to-image',
  path: '/tools/image-to-image',
  getParentRoute: () => SiteRoute,
} as any)
const SiteToolsFashionRoute = SiteToolsFashionRouteImport.update({
  id: '/tools/fashion',
  path: '/tools/fashion',
  getParentRoute: () => SiteRoute,
} as any)
const SiteToolsFaceEnhancerRoute = SiteToolsFaceEnhancerRouteImport.update({
  id: '/tools/face-enhancer',
  path: '/tools/face-enhancer',
  getParentRoute: () => SiteRoute,
} as any)
const SiteToolsBackgroundRemoverRoute =
  SiteToolsBackgroundRemoverRouteImport.update({
    id: '/tools/background-remover',
    path: '/tools/background-remover',
    getParentRoute: () => SiteRoute,
  } as any)
const SiteToolsAvatarRoute = SiteToolsAvatarRouteImport.update({
  id: '/tools/avatar',
  path: '/tools/avatar',
  getParentRoute: () => SiteRoute,
} as any)
const SiteToolsAnimeRoute = SiteToolsAnimeRouteImport.update({
  id: '/tools/anime',
  path: '/tools/anime',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const DashDashboardUploadsRoute = DashDashboardUploadsRouteImport.update({
  id: '/dashboard/uploads',
  path: '/dashboard/uploads',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardTeamRoute = DashDashboardTeamRouteImport.update({
  id: '/dashboard/team',
  path: '/dashboard/team',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardSubscriptionRoute =
  DashDashboardSubscriptionRouteImport.update({
    id: '/dashboard/subscription',
    path: '/dashboard/subscription',
    getParentRoute: () => DashRoute,
  } as any)
const DashDashboardSettingsRoute = DashDashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardScheduledRoute = DashDashboardScheduledRouteImport.update({
  id: '/dashboard/scheduled',
  path: '/dashboard/scheduled',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardReferralsRoute = DashDashboardReferralsRouteImport.update({
  id: '/dashboard/referrals',
  path: '/dashboard/referrals',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardPublicGalleryRoute =
  DashDashboardPublicGalleryRouteImport.update({
    id: '/dashboard/public-gallery',
    path: '/dashboard/public-gallery',
    getParentRoute: () => DashRoute,
  } as any)
const DashDashboardPromptsRoute = DashDashboardPromptsRouteImport.update({
  id: '/dashboard/prompts',
  path: '/dashboard/prompts',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardProfileRoute = DashDashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardNotificationsRoute =
  DashDashboardNotificationsRouteImport.update({
    id: '/dashboard/notifications',
    path: '/dashboard/notifications',
    getParentRoute: () => DashRoute,
  } as any)
const DashDashboardMessagesRoute = DashDashboardMessagesRouteImport.update({
  id: '/dashboard/messages',
  path: '/dashboard/messages',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardHistoryRoute = DashDashboardHistoryRouteImport.update({
  id: '/dashboard/history',
  path: '/dashboard/history',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardGenerateRoute = DashDashboardGenerateRouteImport.update({
  id: '/dashboard/generate',
  path: '/dashboard/generate',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardGalleryRoute = DashDashboardGalleryRouteImport.update({
  id: '/dashboard/gallery',
  path: '/dashboard/gallery',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardFollowingRoute = DashDashboardFollowingRouteImport.update({
  id: '/dashboard/following',
  path: '/dashboard/following',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardFavoritesRoute = DashDashboardFavoritesRouteImport.update({
  id: '/dashboard/favorites',
  path: '/dashboard/favorites',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardEarningsRoute = DashDashboardEarningsRouteImport.update({
  id: '/dashboard/earnings',
  path: '/dashboard/earnings',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardDownloadsRoute = DashDashboardDownloadsRouteImport.update({
  id: '/dashboard/downloads',
  path: '/dashboard/downloads',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardCreditsRoute = DashDashboardCreditsRouteImport.update({
  id: '/dashboard/credits',
  path: '/dashboard/credits',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardCommunityRoute = DashDashboardCommunityRouteImport.update({
  id: '/dashboard/community',
  path: '/dashboard/community',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardCollectionsRoute =
  DashDashboardCollectionsRouteImport.update({
    id: '/dashboard/collections',
    path: '/dashboard/collections',
    getParentRoute: () => DashRoute,
  } as any)
const DashDashboardCanvasRoute = DashDashboardCanvasRouteImport.update({
  id: '/dashboard/canvas',
  path: '/dashboard/canvas',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardBrandKitRoute = DashDashboardBrandKitRouteImport.update({
  id: '/dashboard/brand-kit',
  path: '/dashboard/brand-kit',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardBillingRoute = DashDashboardBillingRouteImport.update({
  id: '/dashboard/billing',
  path: '/dashboard/billing',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardApiKeysRoute = DashDashboardApiKeysRouteImport.update({
  id: '/dashboard/api-keys',
  path: '/dashboard/api-keys',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardAnalyticsRoute = DashDashboardAnalyticsRouteImport.update({
  id: '/dashboard/analytics',
  path: '/dashboard/analytics',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardAiToolsRoute = DashDashboardAiToolsRouteImport.update({
  id: '/dashboard/ai-tools',
  path: '/dashboard/ai-tools',
  getParentRoute: () => DashRoute,
} as any)
const AuthOnboardingThemeRoute = AuthOnboardingThemeRouteImport.update({
  id: '/onboarding/theme',
  path: '/onboarding/theme',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingStyleRoute = AuthOnboardingStyleRouteImport.update({
  id: '/onboarding/style',
  path: '/onboarding/style',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingInterestsRoute = AuthOnboardingInterestsRouteImport.update({
  id: '/onboarding/interests',
  path: '/onboarding/interests',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingFirstPromptRoute =
  AuthOnboardingFirstPromptRouteImport.update({
    id: '/onboarding/first-prompt',
    path: '/onboarding/first-prompt',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthOnboardingCategoriesRoute =
  AuthOnboardingCategoriesRouteImport.update({
    id: '/onboarding/categories',
    path: '/onboarding/categories',
    getParentRoute: () => AuthRoute,
  } as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRevenueRoute = AdminAdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReportedRoute = AdminAdminReportedRouteImport.update({
  id: '/admin/reported',
  path: '/admin/reported',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPlansRoute = AdminAdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminNotificationsRoute = AdminAdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminModerationRoute = AdminAdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminModelsRoute = AdminAdminModelsRouteImport.update({
  id: '/admin/models',
  path: '/admin/models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFeatureFlagsRoute = AdminAdminFeatureFlagsRouteImport.update({
  id: '/admin/feature-flags',
  path: '/admin/feature-flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCreditsRoute = AdminAdminCreditsRouteImport.update({
  id: '/admin/credits',
  path: '/admin/credits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBlogsRoute = AdminAdminBlogsRouteImport.update({
  id: '/admin/blogs',
  path: '/admin/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBannersRoute = AdminAdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/recover': typeof AuthRecoverRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/welcome': typeof AuthWelcomeRoute
  '/about': typeof SiteAboutRoute
  '/affiliate-program': typeof SiteAffiliateProgramRoute
  '/api-access': typeof SiteApiAccessRoute
  '/blogs': typeof SiteBlogsRoute
  '/careers': typeof SiteCareersRoute
  '/challenges': typeof SiteChallengesRoute
  '/changelog': typeof SiteChangelogRoute
  '/community': typeof SiteCommunityRoute
  '/contact': typeof SiteContactRoute
  '/cookies': typeof SiteCookiesRoute
  '/creator-program': typeof SiteCreatorProgramRoute
  '/dmca': typeof SiteDmcaRoute
  '/documentation': typeof SiteDocumentationRoute
  '/enterprise': typeof SiteEnterpriseRoute
  '/events': typeof SiteEventsRoute
  '/explore': typeof SiteExploreRoute
  '/faqs': typeof SiteFaqsRoute
  '/features': typeof SiteFeaturesRoute
  '/help': typeof SiteHelpRoute
  '/integrations': typeof SiteIntegrationsRoute
  '/leaderboard': typeof SiteLeaderboardRoute
  '/models': typeof SiteModelsRoute
  '/new': typeof SiteNewRoute
  '/press-kit': typeof SitePressKitRoute
  '/pricing': typeof SitePricingRoute
  '/privacy': typeof SitePrivacyRoute
  '/prompt-library': typeof SitePromptLibraryRoute
  '/prompt-marketplace': typeof SitePromptMarketplaceRoute
  '/referral-program': typeof SiteReferralProgramRoute
  '/roadmap': typeof SiteRoadmapRoute
  '/showcase': typeof SiteShowcaseRoute
  '/status': typeof SiteStatusRoute
  '/terms': typeof SiteTermsRoute
  '/trending': typeof SiteTrendingRoute
  '/tutorials': typeof SiteTutorialsRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/banners': typeof AdminAdminBannersRoute
  '/admin/blogs': typeof AdminAdminBlogsRoute
  '/admin/credits': typeof AdminAdminCreditsRoute
  '/admin/feature-flags': typeof AdminAdminFeatureFlagsRoute
  '/admin/models': typeof AdminAdminModelsRoute
  '/admin/moderation': typeof AdminAdminModerationRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/plans': typeof AdminAdminPlansRoute
  '/admin/reported': typeof AdminAdminReportedRoute
  '/admin/revenue': typeof AdminAdminRevenueRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/onboarding/categories': typeof AuthOnboardingCategoriesRoute
  '/onboarding/first-prompt': typeof AuthOnboardingFirstPromptRoute
  '/onboarding/interests': typeof AuthOnboardingInterestsRoute
  '/onboarding/style': typeof AuthOnboardingStyleRoute
  '/onboarding/theme': typeof AuthOnboardingThemeRoute
  '/dashboard/ai-tools': typeof DashDashboardAiToolsRoute
  '/dashboard/analytics': typeof DashDashboardAnalyticsRoute
  '/dashboard/api-keys': typeof DashDashboardApiKeysRoute
  '/dashboard/billing': typeof DashDashboardBillingRoute
  '/dashboard/brand-kit': typeof DashDashboardBrandKitRoute
  '/dashboard/canvas': typeof DashDashboardCanvasRoute
  '/dashboard/collections': typeof DashDashboardCollectionsRoute
  '/dashboard/community': typeof DashDashboardCommunityRoute
  '/dashboard/credits': typeof DashDashboardCreditsRoute
  '/dashboard/downloads': typeof DashDashboardDownloadsRoute
  '/dashboard/earnings': typeof DashDashboardEarningsRoute
  '/dashboard/favorites': typeof DashDashboardFavoritesRoute
  '/dashboard/following': typeof DashDashboardFollowingRoute
  '/dashboard/gallery': typeof DashDashboardGalleryRoute
  '/dashboard/generate': typeof DashDashboardGenerateRoute
  '/dashboard/history': typeof DashDashboardHistoryRoute
  '/dashboard/messages': typeof DashDashboardMessagesRoute
  '/dashboard/notifications': typeof DashDashboardNotificationsRoute
  '/dashboard/profile': typeof DashDashboardProfileRoute
  '/dashboard/prompts': typeof DashDashboardPromptsRoute
  '/dashboard/public-gallery': typeof DashDashboardPublicGalleryRoute
  '/dashboard/referrals': typeof DashDashboardReferralsRoute
  '/dashboard/scheduled': typeof DashDashboardScheduledRoute
  '/dashboard/settings': typeof DashDashboardSettingsRoute
  '/dashboard/subscription': typeof DashDashboardSubscriptionRoute
  '/dashboard/team': typeof DashDashboardTeamRoute
  '/dashboard/uploads': typeof DashDashboardUploadsRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/tools/anime': typeof SiteToolsAnimeRoute
  '/tools/avatar': typeof SiteToolsAvatarRoute
  '/tools/background-remover': typeof SiteToolsBackgroundRemoverRoute
  '/tools/face-enhancer': typeof SiteToolsFaceEnhancerRoute
  '/tools/fashion': typeof SiteToolsFashionRoute
  '/tools/image-to-image': typeof SiteToolsImageToImageRoute
  '/tools/interior': typeof SiteToolsInteriorRoute
  '/tools/logo': typeof SiteToolsLogoRoute
  '/tools/mockup': typeof SiteToolsMockupRoute
  '/tools/poster': typeof SiteToolsPosterRoute
  '/tools/prompt-enhancer': typeof SiteToolsPromptEnhancerRoute
  '/tools/sticker': typeof SiteToolsStickerRoute
  '/tools/text-to-image': typeof SiteToolsTextToImageRoute
  '/tools/thumbnail': typeof SiteToolsThumbnailRoute
  '/tools/upscaler': typeof SiteToolsUpscalerRoute
  '/tools/wallpaper': typeof SiteToolsWallpaperRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/dashboard/': typeof DashDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/recover': typeof AuthRecoverRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/welcome': typeof AuthWelcomeRoute
  '/about': typeof SiteAboutRoute
  '/affiliate-program': typeof SiteAffiliateProgramRoute
  '/api-access': typeof SiteApiAccessRoute
  '/blogs': typeof SiteBlogsRoute
  '/careers': typeof SiteCareersRoute
  '/challenges': typeof SiteChallengesRoute
  '/changelog': typeof SiteChangelogRoute
  '/community': typeof SiteCommunityRoute
  '/contact': typeof SiteContactRoute
  '/cookies': typeof SiteCookiesRoute
  '/creator-program': typeof SiteCreatorProgramRoute
  '/dmca': typeof SiteDmcaRoute
  '/documentation': typeof SiteDocumentationRoute
  '/enterprise': typeof SiteEnterpriseRoute
  '/events': typeof SiteEventsRoute
  '/explore': typeof SiteExploreRoute
  '/faqs': typeof SiteFaqsRoute
  '/features': typeof SiteFeaturesRoute
  '/help': typeof SiteHelpRoute
  '/integrations': typeof SiteIntegrationsRoute
  '/leaderboard': typeof SiteLeaderboardRoute
  '/models': typeof SiteModelsRoute
  '/new': typeof SiteNewRoute
  '/press-kit': typeof SitePressKitRoute
  '/pricing': typeof SitePricingRoute
  '/privacy': typeof SitePrivacyRoute
  '/prompt-library': typeof SitePromptLibraryRoute
  '/prompt-marketplace': typeof SitePromptMarketplaceRoute
  '/referral-program': typeof SiteReferralProgramRoute
  '/roadmap': typeof SiteRoadmapRoute
  '/showcase': typeof SiteShowcaseRoute
  '/status': typeof SiteStatusRoute
  '/terms': typeof SiteTermsRoute
  '/trending': typeof SiteTrendingRoute
  '/tutorials': typeof SiteTutorialsRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/banners': typeof AdminAdminBannersRoute
  '/admin/blogs': typeof AdminAdminBlogsRoute
  '/admin/credits': typeof AdminAdminCreditsRoute
  '/admin/feature-flags': typeof AdminAdminFeatureFlagsRoute
  '/admin/models': typeof AdminAdminModelsRoute
  '/admin/moderation': typeof AdminAdminModerationRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/plans': typeof AdminAdminPlansRoute
  '/admin/reported': typeof AdminAdminReportedRoute
  '/admin/revenue': typeof AdminAdminRevenueRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/onboarding/categories': typeof AuthOnboardingCategoriesRoute
  '/onboarding/first-prompt': typeof AuthOnboardingFirstPromptRoute
  '/onboarding/interests': typeof AuthOnboardingInterestsRoute
  '/onboarding/style': typeof AuthOnboardingStyleRoute
  '/onboarding/theme': typeof AuthOnboardingThemeRoute
  '/dashboard/ai-tools': typeof DashDashboardAiToolsRoute
  '/dashboard/analytics': typeof DashDashboardAnalyticsRoute
  '/dashboard/api-keys': typeof DashDashboardApiKeysRoute
  '/dashboard/billing': typeof DashDashboardBillingRoute
  '/dashboard/brand-kit': typeof DashDashboardBrandKitRoute
  '/dashboard/canvas': typeof DashDashboardCanvasRoute
  '/dashboard/collections': typeof DashDashboardCollectionsRoute
  '/dashboard/community': typeof DashDashboardCommunityRoute
  '/dashboard/credits': typeof DashDashboardCreditsRoute
  '/dashboard/downloads': typeof DashDashboardDownloadsRoute
  '/dashboard/earnings': typeof DashDashboardEarningsRoute
  '/dashboard/favorites': typeof DashDashboardFavoritesRoute
  '/dashboard/following': typeof DashDashboardFollowingRoute
  '/dashboard/gallery': typeof DashDashboardGalleryRoute
  '/dashboard/generate': typeof DashDashboardGenerateRoute
  '/dashboard/history': typeof DashDashboardHistoryRoute
  '/dashboard/messages': typeof DashDashboardMessagesRoute
  '/dashboard/notifications': typeof DashDashboardNotificationsRoute
  '/dashboard/profile': typeof DashDashboardProfileRoute
  '/dashboard/prompts': typeof DashDashboardPromptsRoute
  '/dashboard/public-gallery': typeof DashDashboardPublicGalleryRoute
  '/dashboard/referrals': typeof DashDashboardReferralsRoute
  '/dashboard/scheduled': typeof DashDashboardScheduledRoute
  '/dashboard/settings': typeof DashDashboardSettingsRoute
  '/dashboard/subscription': typeof DashDashboardSubscriptionRoute
  '/dashboard/team': typeof DashDashboardTeamRoute
  '/dashboard/uploads': typeof DashDashboardUploadsRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/tools/anime': typeof SiteToolsAnimeRoute
  '/tools/avatar': typeof SiteToolsAvatarRoute
  '/tools/background-remover': typeof SiteToolsBackgroundRemoverRoute
  '/tools/face-enhancer': typeof SiteToolsFaceEnhancerRoute
  '/tools/fashion': typeof SiteToolsFashionRoute
  '/tools/image-to-image': typeof SiteToolsImageToImageRoute
  '/tools/interior': typeof SiteToolsInteriorRoute
  '/tools/logo': typeof SiteToolsLogoRoute
  '/tools/mockup': typeof SiteToolsMockupRoute
  '/tools/poster': typeof SiteToolsPosterRoute
  '/tools/prompt-enhancer': typeof SiteToolsPromptEnhancerRoute
  '/tools/sticker': typeof SiteToolsStickerRoute
  '/tools/text-to-image': typeof SiteToolsTextToImageRoute
  '/tools/thumbnail': typeof SiteToolsThumbnailRoute
  '/tools/upscaler': typeof SiteToolsUpscalerRoute
  '/tools/wallpaper': typeof SiteToolsWallpaperRoute
  '/admin': typeof AdminAdminIndexRoute
  '/dashboard': typeof DashDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_dash': typeof DashRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/recover': typeof AuthRecoverRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_auth/welcome': typeof AuthWelcomeRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/affiliate-program': typeof SiteAffiliateProgramRoute
  '/_site/api-access': typeof SiteApiAccessRoute
  '/_site/blogs': typeof SiteBlogsRoute
  '/_site/careers': typeof SiteCareersRoute
  '/_site/challenges': typeof SiteChallengesRoute
  '/_site/changelog': typeof SiteChangelogRoute
  '/_site/community': typeof SiteCommunityRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/cookies': typeof SiteCookiesRoute
  '/_site/creator-program': typeof SiteCreatorProgramRoute
  '/_site/dmca': typeof SiteDmcaRoute
  '/_site/documentation': typeof SiteDocumentationRoute
  '/_site/enterprise': typeof SiteEnterpriseRoute
  '/_site/events': typeof SiteEventsRoute
  '/_site/explore': typeof SiteExploreRoute
  '/_site/faqs': typeof SiteFaqsRoute
  '/_site/features': typeof SiteFeaturesRoute
  '/_site/help': typeof SiteHelpRoute
  '/_site/integrations': typeof SiteIntegrationsRoute
  '/_site/leaderboard': typeof SiteLeaderboardRoute
  '/_site/models': typeof SiteModelsRoute
  '/_site/new': typeof SiteNewRoute
  '/_site/press-kit': typeof SitePressKitRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/prompt-library': typeof SitePromptLibraryRoute
  '/_site/prompt-marketplace': typeof SitePromptMarketplaceRoute
  '/_site/referral-program': typeof SiteReferralProgramRoute
  '/_site/roadmap': typeof SiteRoadmapRoute
  '/_site/showcase': typeof SiteShowcaseRoute
  '/_site/status': typeof SiteStatusRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/trending': typeof SiteTrendingRoute
  '/_site/tutorials': typeof SiteTutorialsRoute
  '/_site/': typeof SiteIndexRoute
  '/_admin/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin/banners': typeof AdminAdminBannersRoute
  '/_admin/admin/blogs': typeof AdminAdminBlogsRoute
  '/_admin/admin/credits': typeof AdminAdminCreditsRoute
  '/_admin/admin/feature-flags': typeof AdminAdminFeatureFlagsRoute
  '/_admin/admin/models': typeof AdminAdminModelsRoute
  '/_admin/admin/moderation': typeof AdminAdminModerationRoute
  '/_admin/admin/notifications': typeof AdminAdminNotificationsRoute
  '/_admin/admin/plans': typeof AdminAdminPlansRoute
  '/_admin/admin/reported': typeof AdminAdminReportedRoute
  '/_admin/admin/revenue': typeof AdminAdminRevenueRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_auth/onboarding/categories': typeof AuthOnboardingCategoriesRoute
  '/_auth/onboarding/first-prompt': typeof AuthOnboardingFirstPromptRoute
  '/_auth/onboarding/interests': typeof AuthOnboardingInterestsRoute
  '/_auth/onboarding/style': typeof AuthOnboardingStyleRoute
  '/_auth/onboarding/theme': typeof AuthOnboardingThemeRoute
  '/_dash/dashboard/ai-tools': typeof DashDashboardAiToolsRoute
  '/_dash/dashboard/analytics': typeof DashDashboardAnalyticsRoute
  '/_dash/dashboard/api-keys': typeof DashDashboardApiKeysRoute
  '/_dash/dashboard/billing': typeof DashDashboardBillingRoute
  '/_dash/dashboard/brand-kit': typeof DashDashboardBrandKitRoute
  '/_dash/dashboard/canvas': typeof DashDashboardCanvasRoute
  '/_dash/dashboard/collections': typeof DashDashboardCollectionsRoute
  '/_dash/dashboard/community': typeof DashDashboardCommunityRoute
  '/_dash/dashboard/credits': typeof DashDashboardCreditsRoute
  '/_dash/dashboard/downloads': typeof DashDashboardDownloadsRoute
  '/_dash/dashboard/earnings': typeof DashDashboardEarningsRoute
  '/_dash/dashboard/favorites': typeof DashDashboardFavoritesRoute
  '/_dash/dashboard/following': typeof DashDashboardFollowingRoute
  '/_dash/dashboard/gallery': typeof DashDashboardGalleryRoute
  '/_dash/dashboard/generate': typeof DashDashboardGenerateRoute
  '/_dash/dashboard/history': typeof DashDashboardHistoryRoute
  '/_dash/dashboard/messages': typeof DashDashboardMessagesRoute
  '/_dash/dashboard/notifications': typeof DashDashboardNotificationsRoute
  '/_dash/dashboard/profile': typeof DashDashboardProfileRoute
  '/_dash/dashboard/prompts': typeof DashDashboardPromptsRoute
  '/_dash/dashboard/public-gallery': typeof DashDashboardPublicGalleryRoute
  '/_dash/dashboard/referrals': typeof DashDashboardReferralsRoute
  '/_dash/dashboard/scheduled': typeof DashDashboardScheduledRoute
  '/_dash/dashboard/settings': typeof DashDashboardSettingsRoute
  '/_dash/dashboard/subscription': typeof DashDashboardSubscriptionRoute
  '/_dash/dashboard/team': typeof DashDashboardTeamRoute
  '/_dash/dashboard/uploads': typeof DashDashboardUploadsRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/tools/anime': typeof SiteToolsAnimeRoute
  '/_site/tools/avatar': typeof SiteToolsAvatarRoute
  '/_site/tools/background-remover': typeof SiteToolsBackgroundRemoverRoute
  '/_site/tools/face-enhancer': typeof SiteToolsFaceEnhancerRoute
  '/_site/tools/fashion': typeof SiteToolsFashionRoute
  '/_site/tools/image-to-image': typeof SiteToolsImageToImageRoute
  '/_site/tools/interior': typeof SiteToolsInteriorRoute
  '/_site/tools/logo': typeof SiteToolsLogoRoute
  '/_site/tools/mockup': typeof SiteToolsMockupRoute
  '/_site/tools/poster': typeof SiteToolsPosterRoute
  '/_site/tools/prompt-enhancer': typeof SiteToolsPromptEnhancerRoute
  '/_site/tools/sticker': typeof SiteToolsStickerRoute
  '/_site/tools/text-to-image': typeof SiteToolsTextToImageRoute
  '/_site/tools/thumbnail': typeof SiteToolsThumbnailRoute
  '/_site/tools/upscaler': typeof SiteToolsUpscalerRoute
  '/_site/tools/wallpaper': typeof SiteToolsWallpaperRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_dash/dashboard/': typeof DashDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/recover'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/verify-otp'
    | '/welcome'
    | '/about'
    | '/affiliate-program'
    | '/api-access'
    | '/blogs'
    | '/careers'
    | '/challenges'
    | '/changelog'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/creator-program'
    | '/dmca'
    | '/documentation'
    | '/enterprise'
    | '/events'
    | '/explore'
    | '/faqs'
    | '/features'
    | '/help'
    | '/integrations'
    | '/leaderboard'
    | '/models'
    | '/new'
    | '/press-kit'
    | '/pricing'
    | '/privacy'
    | '/prompt-library'
    | '/prompt-marketplace'
    | '/referral-program'
    | '/roadmap'
    | '/showcase'
    | '/status'
    | '/terms'
    | '/trending'
    | '/tutorials'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/blogs'
    | '/admin/credits'
    | '/admin/feature-flags'
    | '/admin/models'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/reported'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/onboarding/categories'
    | '/onboarding/first-prompt'
    | '/onboarding/interests'
    | '/onboarding/style'
    | '/onboarding/theme'
    | '/dashboard/ai-tools'
    | '/dashboard/analytics'
    | '/dashboard/api-keys'
    | '/dashboard/billing'
    | '/dashboard/brand-kit'
    | '/dashboard/canvas'
    | '/dashboard/collections'
    | '/dashboard/community'
    | '/dashboard/credits'
    | '/dashboard/downloads'
    | '/dashboard/earnings'
    | '/dashboard/favorites'
    | '/dashboard/following'
    | '/dashboard/gallery'
    | '/dashboard/generate'
    | '/dashboard/history'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/prompts'
    | '/dashboard/public-gallery'
    | '/dashboard/referrals'
    | '/dashboard/scheduled'
    | '/dashboard/settings'
    | '/dashboard/subscription'
    | '/dashboard/team'
    | '/dashboard/uploads'
    | '/blog/$slug'
    | '/tools/anime'
    | '/tools/avatar'
    | '/tools/background-remover'
    | '/tools/face-enhancer'
    | '/tools/fashion'
    | '/tools/image-to-image'
    | '/tools/interior'
    | '/tools/logo'
    | '/tools/mockup'
    | '/tools/poster'
    | '/tools/prompt-enhancer'
    | '/tools/sticker'
    | '/tools/text-to-image'
    | '/tools/thumbnail'
    | '/tools/upscaler'
    | '/tools/wallpaper'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/recover'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/verify-otp'
    | '/welcome'
    | '/about'
    | '/affiliate-program'
    | '/api-access'
    | '/blogs'
    | '/careers'
    | '/challenges'
    | '/changelog'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/creator-program'
    | '/dmca'
    | '/documentation'
    | '/enterprise'
    | '/events'
    | '/explore'
    | '/faqs'
    | '/features'
    | '/help'
    | '/integrations'
    | '/leaderboard'
    | '/models'
    | '/new'
    | '/press-kit'
    | '/pricing'
    | '/privacy'
    | '/prompt-library'
    | '/prompt-marketplace'
    | '/referral-program'
    | '/roadmap'
    | '/showcase'
    | '/status'
    | '/terms'
    | '/trending'
    | '/tutorials'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/blogs'
    | '/admin/credits'
    | '/admin/feature-flags'
    | '/admin/models'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/reported'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/onboarding/categories'
    | '/onboarding/first-prompt'
    | '/onboarding/interests'
    | '/onboarding/style'
    | '/onboarding/theme'
    | '/dashboard/ai-tools'
    | '/dashboard/analytics'
    | '/dashboard/api-keys'
    | '/dashboard/billing'
    | '/dashboard/brand-kit'
    | '/dashboard/canvas'
    | '/dashboard/collections'
    | '/dashboard/community'
    | '/dashboard/credits'
    | '/dashboard/downloads'
    | '/dashboard/earnings'
    | '/dashboard/favorites'
    | '/dashboard/following'
    | '/dashboard/gallery'
    | '/dashboard/generate'
    | '/dashboard/history'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/prompts'
    | '/dashboard/public-gallery'
    | '/dashboard/referrals'
    | '/dashboard/scheduled'
    | '/dashboard/settings'
    | '/dashboard/subscription'
    | '/dashboard/team'
    | '/dashboard/uploads'
    | '/blog/$slug'
    | '/tools/anime'
    | '/tools/avatar'
    | '/tools/background-remover'
    | '/tools/face-enhancer'
    | '/tools/fashion'
    | '/tools/image-to-image'
    | '/tools/interior'
    | '/tools/logo'
    | '/tools/mockup'
    | '/tools/poster'
    | '/tools/prompt-enhancer'
    | '/tools/sticker'
    | '/tools/text-to-image'
    | '/tools/thumbnail'
    | '/tools/upscaler'
    | '/tools/wallpaper'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_dash'
    | '/_site'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/recover'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/_auth/verify-otp'
    | '/_auth/welcome'
    | '/_site/about'
    | '/_site/affiliate-program'
    | '/_site/api-access'
    | '/_site/blogs'
    | '/_site/careers'
    | '/_site/challenges'
    | '/_site/changelog'
    | '/_site/community'
    | '/_site/contact'
    | '/_site/cookies'
    | '/_site/creator-program'
    | '/_site/dmca'
    | '/_site/documentation'
    | '/_site/enterprise'
    | '/_site/events'
    | '/_site/explore'
    | '/_site/faqs'
    | '/_site/features'
    | '/_site/help'
    | '/_site/integrations'
    | '/_site/leaderboard'
    | '/_site/models'
    | '/_site/new'
    | '/_site/press-kit'
    | '/_site/pricing'
    | '/_site/privacy'
    | '/_site/prompt-library'
    | '/_site/prompt-marketplace'
    | '/_site/referral-program'
    | '/_site/roadmap'
    | '/_site/showcase'
    | '/_site/status'
    | '/_site/terms'
    | '/_site/trending'
    | '/_site/tutorials'
    | '/_site/'
    | '/_admin/admin/analytics'
    | '/_admin/admin/banners'
    | '/_admin/admin/blogs'
    | '/_admin/admin/credits'
    | '/_admin/admin/feature-flags'
    | '/_admin/admin/models'
    | '/_admin/admin/moderation'
    | '/_admin/admin/notifications'
    | '/_admin/admin/plans'
    | '/_admin/admin/reported'
    | '/_admin/admin/revenue'
    | '/_admin/admin/settings'
    | '/_admin/admin/users'
    | '/_auth/onboarding/categories'
    | '/_auth/onboarding/first-prompt'
    | '/_auth/onboarding/interests'
    | '/_auth/onboarding/style'
    | '/_auth/onboarding/theme'
    | '/_dash/dashboard/ai-tools'
    | '/_dash/dashboard/analytics'
    | '/_dash/dashboard/api-keys'
    | '/_dash/dashboard/billing'
    | '/_dash/dashboard/brand-kit'
    | '/_dash/dashboard/canvas'
    | '/_dash/dashboard/collections'
    | '/_dash/dashboard/community'
    | '/_dash/dashboard/credits'
    | '/_dash/dashboard/downloads'
    | '/_dash/dashboard/earnings'
    | '/_dash/dashboard/favorites'
    | '/_dash/dashboard/following'
    | '/_dash/dashboard/gallery'
    | '/_dash/dashboard/generate'
    | '/_dash/dashboard/history'
    | '/_dash/dashboard/messages'
    | '/_dash/dashboard/notifications'
    | '/_dash/dashboard/profile'
    | '/_dash/dashboard/prompts'
    | '/_dash/dashboard/public-gallery'
    | '/_dash/dashboard/referrals'
    | '/_dash/dashboard/scheduled'
    | '/_dash/dashboard/settings'
    | '/_dash/dashboard/subscription'
    | '/_dash/dashboard/team'
    | '/_dash/dashboard/uploads'
    | '/_site/blog/$slug'
    | '/_site/tools/anime'
    | '/_site/tools/avatar'
    | '/_site/tools/background-remover'
    | '/_site/tools/face-enhancer'
    | '/_site/tools/fashion'
    | '/_site/tools/image-to-image'
    | '/_site/tools/interior'
    | '/_site/tools/logo'
    | '/_site/tools/mockup'
    | '/_site/tools/poster'
    | '/_site/tools/prompt-enhancer'
    | '/_site/tools/sticker'
    | '/_site/tools/text-to-image'
    | '/_site/tools/thumbnail'
    | '/_site/tools/upscaler'
    | '/_site/tools/wallpaper'
    | '/_admin/admin/'
    | '/_dash/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashRoute: typeof DashRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tutorials': {
      id: '/_site/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof SiteTutorialsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/trending': {
      id: '/_site/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof SiteTrendingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/status': {
      id: '/_site/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof SiteStatusRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/showcase': {
      id: '/_site/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof SiteShowcaseRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/roadmap': {
      id: '/_site/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof SiteRoadmapRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/referral-program': {
      id: '/_site/referral-program'
      path: '/referral-program'
      fullPath: '/referral-program'
      preLoaderRoute: typeof SiteReferralProgramRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/prompt-marketplace': {
      id: '/_site/prompt-marketplace'
      path: '/prompt-marketplace'
      fullPath: '/prompt-marketplace'
      preLoaderRoute: typeof SitePromptMarketplaceRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/prompt-library': {
      id: '/_site/prompt-library'
      path: '/prompt-library'
      fullPath: '/prompt-library'
      preLoaderRoute: typeof SitePromptLibraryRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/press-kit': {
      id: '/_site/press-kit'
      path: '/press-kit'
      fullPath: '/press-kit'
      preLoaderRoute: typeof SitePressKitRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/new': {
      id: '/_site/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof SiteNewRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/models': {
      id: '/_site/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof SiteModelsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/leaderboard': {
      id: '/_site/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof SiteLeaderboardRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/integrations': {
      id: '/_site/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof SiteIntegrationsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/help': {
      id: '/_site/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof SiteHelpRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/features': {
      id: '/_site/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof SiteFeaturesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faqs': {
      id: '/_site/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof SiteFaqsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/explore': {
      id: '/_site/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof SiteExploreRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/events': {
      id: '/_site/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof SiteEventsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/enterprise': {
      id: '/_site/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof SiteEnterpriseRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/documentation': {
      id: '/_site/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof SiteDocumentationRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/dmca': {
      id: '/_site/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof SiteDmcaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/creator-program': {
      id: '/_site/creator-program'
      path: '/creator-program'
      fullPath: '/creator-program'
      preLoaderRoute: typeof SiteCreatorProgramRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cookies': {
      id: '/_site/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof SiteCookiesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/community': {
      id: '/_site/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof SiteCommunityRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/changelog': {
      id: '/_site/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof SiteChangelogRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/challenges': {
      id: '/_site/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof SiteChallengesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/careers': {
      id: '/_site/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof SiteCareersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blogs': {
      id: '/_site/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof SiteBlogsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/api-access': {
      id: '/_site/api-access'
      path: '/api-access'
      fullPath: '/api-access'
      preLoaderRoute: typeof SiteApiAccessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/affiliate-program': {
      id: '/_site/affiliate-program'
      path: '/affiliate-program'
      fullPath: '/affiliate-program'
      preLoaderRoute: typeof SiteAffiliateProgramRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_auth/welcome': {
      id: '/_auth/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthWelcomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/recover': {
      id: '/_auth/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof AuthRecoverRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dash/dashboard/': {
      id: '/_dash/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashDashboardIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/tools/wallpaper': {
      id: '/_site/tools/wallpaper'
      path: '/tools/wallpaper'
      fullPath: '/tools/wallpaper'
      preLoaderRoute: typeof SiteToolsWallpaperRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/upscaler': {
      id: '/_site/tools/upscaler'
      path: '/tools/upscaler'
      fullPath: '/tools/upscaler'
      preLoaderRoute: typeof SiteToolsUpscalerRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/thumbnail': {
      id: '/_site/tools/thumbnail'
      path: '/tools/thumbnail'
      fullPath: '/tools/thumbnail'
      preLoaderRoute: typeof SiteToolsThumbnailRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/text-to-image': {
      id: '/_site/tools/text-to-image'
      path: '/tools/text-to-image'
      fullPath: '/tools/text-to-image'
      preLoaderRoute: typeof SiteToolsTextToImageRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/sticker': {
      id: '/_site/tools/sticker'
      path: '/tools/sticker'
      fullPath: '/tools/sticker'
      preLoaderRoute: typeof SiteToolsStickerRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/prompt-enhancer': {
      id: '/_site/tools/prompt-enhancer'
      path: '/tools/prompt-enhancer'
      fullPath: '/tools/prompt-enhancer'
      preLoaderRoute: typeof SiteToolsPromptEnhancerRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/poster': {
      id: '/_site/tools/poster'
      path: '/tools/poster'
      fullPath: '/tools/poster'
      preLoaderRoute: typeof SiteToolsPosterRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/mockup': {
      id: '/_site/tools/mockup'
      path: '/tools/mockup'
      fullPath: '/tools/mockup'
      preLoaderRoute: typeof SiteToolsMockupRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/logo': {
      id: '/_site/tools/logo'
      path: '/tools/logo'
      fullPath: '/tools/logo'
      preLoaderRoute: typeof SiteToolsLogoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/interior': {
      id: '/_site/tools/interior'
      path: '/tools/interior'
      fullPath: '/tools/interior'
      preLoaderRoute: typeof SiteToolsInteriorRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/image-to-image': {
      id: '/_site/tools/image-to-image'
      path: '/tools/image-to-image'
      fullPath: '/tools/image-to-image'
      preLoaderRoute: typeof SiteToolsImageToImageRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/fashion': {
      id: '/_site/tools/fashion'
      path: '/tools/fashion'
      fullPath: '/tools/fashion'
      preLoaderRoute: typeof SiteToolsFashionRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/face-enhancer': {
      id: '/_site/tools/face-enhancer'
      path: '/tools/face-enhancer'
      fullPath: '/tools/face-enhancer'
      preLoaderRoute: typeof SiteToolsFaceEnhancerRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/background-remover': {
      id: '/_site/tools/background-remover'
      path: '/tools/background-remover'
      fullPath: '/tools/background-remover'
      preLoaderRoute: typeof SiteToolsBackgroundRemoverRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/avatar': {
      id: '/_site/tools/avatar'
      path: '/tools/avatar'
      fullPath: '/tools/avatar'
      preLoaderRoute: typeof SiteToolsAvatarRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tools/anime': {
      id: '/_site/tools/anime'
      path: '/tools/anime'
      fullPath: '/tools/anime'
      preLoaderRoute: typeof SiteToolsAnimeRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_dash/dashboard/uploads': {
      id: '/_dash/dashboard/uploads'
      path: '/dashboard/uploads'
      fullPath: '/dashboard/uploads'
      preLoaderRoute: typeof DashDashboardUploadsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/team': {
      id: '/_dash/dashboard/team'
      path: '/dashboard/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashDashboardTeamRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/subscription': {
      id: '/_dash/dashboard/subscription'
      path: '/dashboard/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof DashDashboardSubscriptionRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/settings': {
      id: '/_dash/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashDashboardSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/scheduled': {
      id: '/_dash/dashboard/scheduled'
      path: '/dashboard/scheduled'
      fullPath: '/dashboard/scheduled'
      preLoaderRoute: typeof DashDashboardScheduledRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/referrals': {
      id: '/_dash/dashboard/referrals'
      path: '/dashboard/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashDashboardReferralsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/public-gallery': {
      id: '/_dash/dashboard/public-gallery'
      path: '/dashboard/public-gallery'
      fullPath: '/dashboard/public-gallery'
      preLoaderRoute: typeof DashDashboardPublicGalleryRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/prompts': {
      id: '/_dash/dashboard/prompts'
      path: '/dashboard/prompts'
      fullPath: '/dashboard/prompts'
      preLoaderRoute: typeof DashDashboardPromptsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/profile': {
      id: '/_dash/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashDashboardProfileRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/notifications': {
      id: '/_dash/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashDashboardNotificationsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/messages': {
      id: '/_dash/dashboard/messages'
      path: '/dashboard/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashDashboardMessagesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/history': {
      id: '/_dash/dashboard/history'
      path: '/dashboard/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashDashboardHistoryRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/generate': {
      id: '/_dash/dashboard/generate'
      path: '/dashboard/generate'
      fullPath: '/dashboard/generate'
      preLoaderRoute: typeof DashDashboardGenerateRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/gallery': {
      id: '/_dash/dashboard/gallery'
      path: '/dashboard/gallery'
      fullPath: '/dashboard/gallery'
      preLoaderRoute: typeof DashDashboardGalleryRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/following': {
      id: '/_dash/dashboard/following'
      path: '/dashboard/following'
      fullPath: '/dashboard/following'
      preLoaderRoute: typeof DashDashboardFollowingRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/favorites': {
      id: '/_dash/dashboard/favorites'
      path: '/dashboard/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashDashboardFavoritesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/earnings': {
      id: '/_dash/dashboard/earnings'
      path: '/dashboard/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof DashDashboardEarningsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/downloads': {
      id: '/_dash/dashboard/downloads'
      path: '/dashboard/downloads'
      fullPath: '/dashboard/downloads'
      preLoaderRoute: typeof DashDashboardDownloadsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/credits': {
      id: '/_dash/dashboard/credits'
      path: '/dashboard/credits'
      fullPath: '/dashboard/credits'
      preLoaderRoute: typeof DashDashboardCreditsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/community': {
      id: '/_dash/dashboard/community'
      path: '/dashboard/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashDashboardCommunityRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/collections': {
      id: '/_dash/dashboard/collections'
      path: '/dashboard/collections'
      fullPath: '/dashboard/collections'
      preLoaderRoute: typeof DashDashboardCollectionsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/canvas': {
      id: '/_dash/dashboard/canvas'
      path: '/dashboard/canvas'
      fullPath: '/dashboard/canvas'
      preLoaderRoute: typeof DashDashboardCanvasRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/brand-kit': {
      id: '/_dash/dashboard/brand-kit'
      path: '/dashboard/brand-kit'
      fullPath: '/dashboard/brand-kit'
      preLoaderRoute: typeof DashDashboardBrandKitRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/billing': {
      id: '/_dash/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashDashboardBillingRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/api-keys': {
      id: '/_dash/dashboard/api-keys'
      path: '/dashboard/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashDashboardApiKeysRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/analytics': {
      id: '/_dash/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashDashboardAnalyticsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard/ai-tools': {
      id: '/_dash/dashboard/ai-tools'
      path: '/dashboard/ai-tools'
      fullPath: '/dashboard/ai-tools'
      preLoaderRoute: typeof DashDashboardAiToolsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_auth/onboarding/theme': {
      id: '/_auth/onboarding/theme'
      path: '/onboarding/theme'
      fullPath: '/onboarding/theme'
      preLoaderRoute: typeof AuthOnboardingThemeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding/style': {
      id: '/_auth/onboarding/style'
      path: '/onboarding/style'
      fullPath: '/onboarding/style'
      preLoaderRoute: typeof AuthOnboardingStyleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding/interests': {
      id: '/_auth/onboarding/interests'
      path: '/onboarding/interests'
      fullPath: '/onboarding/interests'
      preLoaderRoute: typeof AuthOnboardingInterestsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding/first-prompt': {
      id: '/_auth/onboarding/first-prompt'
      path: '/onboarding/first-prompt'
      fullPath: '/onboarding/first-prompt'
      preLoaderRoute: typeof AuthOnboardingFirstPromptRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding/categories': {
      id: '/_auth/onboarding/categories'
      path: '/onboarding/categories'
      fullPath: '/onboarding/categories'
      preLoaderRoute: typeof AuthOnboardingCategoriesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/revenue': {
      id: '/_admin/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminAdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reported': {
      id: '/_admin/admin/reported'
      path: '/admin/reported'
      fullPath: '/admin/reported'
      preLoaderRoute: typeof AdminAdminReportedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/plans': {
      id: '/_admin/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminAdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/notifications': {
      id: '/_admin/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminAdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/moderation': {
      id: '/_admin/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminAdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/models': {
      id: '/_admin/admin/models'
      path: '/admin/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminAdminModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/feature-flags': {
      id: '/_admin/admin/feature-flags'
      path: '/admin/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminAdminFeatureFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/credits': {
      id: '/_admin/admin/credits'
      path: '/admin/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AdminAdminCreditsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/blogs': {
      id: '/_admin/admin/blogs'
      path: '/admin/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminAdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/banners': {
      id: '/_admin/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminAdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/analytics': {
      id: '/_admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminBannersRoute: typeof AdminAdminBannersRoute
  AdminAdminBlogsRoute: typeof AdminAdminBlogsRoute
  AdminAdminCreditsRoute: typeof AdminAdminCreditsRoute
  AdminAdminFeatureFlagsRoute: typeof AdminAdminFeatureFlagsRoute
  AdminAdminModelsRoute: typeof AdminAdminModelsRoute
  AdminAdminModerationRoute: typeof AdminAdminModerationRoute
  AdminAdminNotificationsRoute: typeof AdminAdminNotificationsRoute
  AdminAdminPlansRoute: typeof AdminAdminPlansRoute
  AdminAdminReportedRoute: typeof AdminAdminReportedRoute
  AdminAdminRevenueRoute: typeof AdminAdminRevenueRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminBannersRoute: AdminAdminBannersRoute,
  AdminAdminBlogsRoute: AdminAdminBlogsRoute,
  AdminAdminCreditsRoute: AdminAdminCreditsRoute,
  AdminAdminFeatureFlagsRoute: AdminAdminFeatureFlagsRoute,
  AdminAdminModelsRoute: AdminAdminModelsRoute,
  AdminAdminModerationRoute: AdminAdminModerationRoute,
  AdminAdminNotificationsRoute: AdminAdminNotificationsRoute,
  AdminAdminPlansRoute: AdminAdminPlansRoute,
  AdminAdminReportedRoute: AdminAdminReportedRoute,
  AdminAdminRevenueRoute: AdminAdminRevenueRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoverRoute: typeof AuthRecoverRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  AuthWelcomeRoute: typeof AuthWelcomeRoute
  AuthOnboardingCategoriesRoute: typeof AuthOnboardingCategoriesRoute
  AuthOnboardingFirstPromptRoute: typeof AuthOnboardingFirstPromptRoute
  AuthOnboardingInterestsRoute: typeof AuthOnboardingInterestsRoute
  AuthOnboardingStyleRoute: typeof AuthOnboardingStyleRoute
  AuthOnboardingThemeRoute: typeof AuthOnboardingThemeRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoverRoute: AuthRecoverRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  AuthWelcomeRoute: AuthWelcomeRoute,
  AuthOnboardingCategoriesRoute: AuthOnboardingCategoriesRoute,
  AuthOnboardingFirstPromptRoute: AuthOnboardingFirstPromptRoute,
  AuthOnboardingInterestsRoute: AuthOnboardingInterestsRoute,
  AuthOnboardingStyleRoute: AuthOnboardingStyleRoute,
  AuthOnboardingThemeRoute: AuthOnboardingThemeRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashRouteChildren {
  DashDashboardAiToolsRoute: typeof DashDashboardAiToolsRoute
  DashDashboardAnalyticsRoute: typeof DashDashboardAnalyticsRoute
  DashDashboardApiKeysRoute: typeof DashDashboardApiKeysRoute
  DashDashboardBillingRoute: typeof DashDashboardBillingRoute
  DashDashboardBrandKitRoute: typeof DashDashboardBrandKitRoute
  DashDashboardCanvasRoute: typeof DashDashboardCanvasRoute
  DashDashboardCollectionsRoute: typeof DashDashboardCollectionsRoute
  DashDashboardCommunityRoute: typeof DashDashboardCommunityRoute
  DashDashboardCreditsRoute: typeof DashDashboardCreditsRoute
  DashDashboardDownloadsRoute: typeof DashDashboardDownloadsRoute
  DashDashboardEarningsRoute: typeof DashDashboardEarningsRoute
  DashDashboardFavoritesRoute: typeof DashDashboardFavoritesRoute
  DashDashboardFollowingRoute: typeof DashDashboardFollowingRoute
  DashDashboardGalleryRoute: typeof DashDashboardGalleryRoute
  DashDashboardGenerateRoute: typeof DashDashboardGenerateRoute
  DashDashboardHistoryRoute: typeof DashDashboardHistoryRoute
  DashDashboardMessagesRoute: typeof DashDashboardMessagesRoute
  DashDashboardNotificationsRoute: typeof DashDashboardNotificationsRoute
  DashDashboardProfileRoute: typeof DashDashboardProfileRoute
  DashDashboardPromptsRoute: typeof DashDashboardPromptsRoute
  DashDashboardPublicGalleryRoute: typeof DashDashboardPublicGalleryRoute
  DashDashboardReferralsRoute: typeof DashDashboardReferralsRoute
  DashDashboardScheduledRoute: typeof DashDashboardScheduledRoute
  DashDashboardSettingsRoute: typeof DashDashboardSettingsRoute
  DashDashboardSubscriptionRoute: typeof DashDashboardSubscriptionRoute
  DashDashboardTeamRoute: typeof DashDashboardTeamRoute
  DashDashboardUploadsRoute: typeof DashDashboardUploadsRoute
  DashDashboardIndexRoute: typeof DashDashboardIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashDashboardAiToolsRoute: DashDashboardAiToolsRoute,
  DashDashboardAnalyticsRoute: DashDashboardAnalyticsRoute,
  DashDashboardApiKeysRoute: DashDashboardApiKeysRoute,
  DashDashboardBillingRoute: DashDashboardBillingRoute,
  DashDashboardBrandKitRoute: DashDashboardBrandKitRoute,
  DashDashboardCanvasRoute: DashDashboardCanvasRoute,
  DashDashboardCollectionsRoute: DashDashboardCollectionsRoute,
  DashDashboardCommunityRoute: DashDashboardCommunityRoute,
  DashDashboardCreditsRoute: DashDashboardCreditsRoute,
  DashDashboardDownloadsRoute: DashDashboardDownloadsRoute,
  DashDashboardEarningsRoute: DashDashboardEarningsRoute,
  DashDashboardFavoritesRoute: DashDashboardFavoritesRoute,
  DashDashboardFollowingRoute: DashDashboardFollowingRoute,
  DashDashboardGalleryRoute: DashDashboardGalleryRoute,
  DashDashboardGenerateRoute: DashDashboardGenerateRoute,
  DashDashboardHistoryRoute: DashDashboardHistoryRoute,
  DashDashboardMessagesRoute: DashDashboardMessagesRoute,
  DashDashboardNotificationsRoute: DashDashboardNotificationsRoute,
  DashDashboardProfileRoute: DashDashboardProfileRoute,
  DashDashboardPromptsRoute: DashDashboardPromptsRoute,
  DashDashboardPublicGalleryRoute: DashDashboardPublicGalleryRoute,
  DashDashboardReferralsRoute: DashDashboardReferralsRoute,
  DashDashboardScheduledRoute: DashDashboardScheduledRoute,
  DashDashboardSettingsRoute: DashDashboardSettingsRoute,
  DashDashboardSubscriptionRoute: DashDashboardSubscriptionRoute,
  DashDashboardTeamRoute: DashDashboardTeamRoute,
  DashDashboardUploadsRoute: DashDashboardUploadsRoute,
  DashDashboardIndexRoute: DashDashboardIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteAffiliateProgramRoute: typeof SiteAffiliateProgramRoute
  SiteApiAccessRoute: typeof SiteApiAccessRoute
  SiteBlogsRoute: typeof SiteBlogsRoute
  SiteCareersRoute: typeof SiteCareersRoute
  SiteChallengesRoute: typeof SiteChallengesRoute
  SiteChangelogRoute: typeof SiteChangelogRoute
  SiteCommunityRoute: typeof SiteCommunityRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteCookiesRoute: typeof SiteCookiesRoute
  SiteCreatorProgramRoute: typeof SiteCreatorProgramRoute
  SiteDmcaRoute: typeof SiteDmcaRoute
  SiteDocumentationRoute: typeof SiteDocumentationRoute
  SiteEnterpriseRoute: typeof SiteEnterpriseRoute
  SiteEventsRoute: typeof SiteEventsRoute
  SiteExploreRoute: typeof SiteExploreRoute
  SiteFaqsRoute: typeof SiteFaqsRoute
  SiteFeaturesRoute: typeof SiteFeaturesRoute
  SiteHelpRoute: typeof SiteHelpRoute
  SiteIntegrationsRoute: typeof SiteIntegrationsRoute
  SiteLeaderboardRoute: typeof SiteLeaderboardRoute
  SiteModelsRoute: typeof SiteModelsRoute
  SiteNewRoute: typeof SiteNewRoute
  SitePressKitRoute: typeof SitePressKitRoute
  SitePricingRoute: typeof SitePricingRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SitePromptLibraryRoute: typeof SitePromptLibraryRoute
  SitePromptMarketplaceRoute: typeof SitePromptMarketplaceRoute
  SiteReferralProgramRoute: typeof SiteReferralProgramRoute
  SiteRoadmapRoute: typeof SiteRoadmapRoute
  SiteShowcaseRoute: typeof SiteShowcaseRoute
  SiteStatusRoute: typeof SiteStatusRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteTrendingRoute: typeof SiteTrendingRoute
  SiteTutorialsRoute: typeof SiteTutorialsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteToolsAnimeRoute: typeof SiteToolsAnimeRoute
  SiteToolsAvatarRoute: typeof SiteToolsAvatarRoute
  SiteToolsBackgroundRemoverRoute: typeof SiteToolsBackgroundRemoverRoute
  SiteToolsFaceEnhancerRoute: typeof SiteToolsFaceEnhancerRoute
  SiteToolsFashionRoute: typeof SiteToolsFashionRoute
  SiteToolsImageToImageRoute: typeof SiteToolsImageToImageRoute
  SiteToolsInteriorRoute: typeof SiteToolsInteriorRoute
  SiteToolsLogoRoute: typeof SiteToolsLogoRoute
  SiteToolsMockupRoute: typeof SiteToolsMockupRoute
  SiteToolsPosterRoute: typeof SiteToolsPosterRoute
  SiteToolsPromptEnhancerRoute: typeof SiteToolsPromptEnhancerRoute
  SiteToolsStickerRoute: typeof SiteToolsStickerRoute
  SiteToolsTextToImageRoute: typeof SiteToolsTextToImageRoute
  SiteToolsThumbnailRoute: typeof SiteToolsThumbnailRoute
  SiteToolsUpscalerRoute: typeof SiteToolsUpscalerRoute
  SiteToolsWallpaperRoute: typeof SiteToolsWallpaperRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteAffiliateProgramRoute: SiteAffiliateProgramRoute,
  SiteApiAccessRoute: SiteApiAccessRoute,
  SiteBlogsRoute: SiteBlogsRoute,
  SiteCareersRoute: SiteCareersRoute,
  SiteChallengesRoute: SiteChallengesRoute,
  SiteChangelogRoute: SiteChangelogRoute,
  SiteCommunityRoute: SiteCommunityRoute,
  SiteContactRoute: SiteContactRoute,
  SiteCookiesRoute: SiteCookiesRoute,
  SiteCreatorProgramRoute: SiteCreatorProgramRoute,
  SiteDmcaRoute: SiteDmcaRoute,
  SiteDocumentationRoute: SiteDocumentationRoute,
  SiteEnterpriseRoute: SiteEnterpriseRoute,
  SiteEventsRoute: SiteEventsRoute,
  SiteExploreRoute: SiteExploreRoute,
  SiteFaqsRoute: SiteFaqsRoute,
  SiteFeaturesRoute: SiteFeaturesRoute,
  SiteHelpRoute: SiteHelpRoute,
  SiteIntegrationsRoute: SiteIntegrationsRoute,
  SiteLeaderboardRoute: SiteLeaderboardRoute,
  SiteModelsRoute: SiteModelsRoute,
  SiteNewRoute: SiteNewRoute,
  SitePressKitRoute: SitePressKitRoute,
  SitePricingRoute: SitePricingRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SitePromptLibraryRoute: SitePromptLibraryRoute,
  SitePromptMarketplaceRoute: SitePromptMarketplaceRoute,
  SiteReferralProgramRoute: SiteReferralProgramRoute,
  SiteRoadmapRoute: SiteRoadmapRoute,
  SiteShowcaseRoute: SiteShowcaseRoute,
  SiteStatusRoute: SiteStatusRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteTrendingRoute: SiteTrendingRoute,
  SiteTutorialsRoute: SiteTutorialsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteToolsAnimeRoute: SiteToolsAnimeRoute,
  SiteToolsAvatarRoute: SiteToolsAvatarRoute,
  SiteToolsBackgroundRemoverRoute: SiteToolsBackgroundRemoverRoute,
  SiteToolsFaceEnhancerRoute: SiteToolsFaceEnhancerRoute,
  SiteToolsFashionRoute: SiteToolsFashionRoute,
  SiteToolsImageToImageRoute: SiteToolsImageToImageRoute,
  SiteToolsInteriorRoute: SiteToolsInteriorRoute,
  SiteToolsLogoRoute: SiteToolsLogoRoute,
  SiteToolsMockupRoute: SiteToolsMockupRoute,
  SiteToolsPosterRoute: SiteToolsPosterRoute,
  SiteToolsPromptEnhancerRoute: SiteToolsPromptEnhancerRoute,
  SiteToolsStickerRoute: SiteToolsStickerRoute,
  SiteToolsTextToImageRoute: SiteToolsTextToImageRoute,
  SiteToolsThumbnailRoute: SiteToolsThumbnailRoute,
  SiteToolsUpscalerRoute: SiteToolsUpscalerRoute,
  SiteToolsWallpaperRoute: SiteToolsWallpaperRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashRoute: DashRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
